# Timeout for commands executed by starship (in milliseconds).
command_timeout = 3600000

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 500

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$battery\
$line_break\
$character\
"""

add_newline = false

[username]
show_always = true
format = '[$user ]($style)'
disabled = false

[directory]
style = "bold cyan"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "* "
style = "bold purple"

[git_status]
style = "bold red"
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = " " # fills with space and pushes battery right

[battery]
disabled = false
charging_symbol = "+(bold green) "
discharging_symbol = "-(bold yellow) "
empty_symbol = "!(bold red) "

[[battery.display]]
threshold = 30
style = "bold red"

[[battery.display]]
threshold = 100
style = "bold yellow"

[character]
success_symbol = "[>](bold green) "
error_symbol = "[>](bold red) "

[package]
disabled = true
[python]
disabled = true
[nodejs]
disabled = true
[lua]
disabled = true
[rust]
disabled = true
